Repository AppleMangoPlate/AppleMangoPlate_Backend, pull requests merged in 2023-11, with the labels that each got.

#18 [fix] #17 category 중복데이터 오류 수정
  src/main/java/com/Applemango_Backend/search/service/CategoryService.java
Labels: fix, 조종현

#20 [refactor] #19 StorageConfig 로직 개선
  src/main/java/com/Applemango_Backend/image/config/StorageConfig.java
Labels: refactor, 조종현

#22 [fix] #21 login password 검증 수정
  src/main/java/com/Applemango_Backend/auth/service/UserService.java
Labels: fix, 조종현

#24 [feat] #23 마이페이지
  src/main/java/com/Applemango_Backend/auth/controller/JwtLoginController.java
  src/main/java/com/Applemango_Backend/auth/controller/UserController.java
  src/main/java/com/Applemango_Backend/auth/domain/User.java
  src/main/java/com/Applemango_Backend/auth/dto/request/JoinRequest.java
  src/main/java/com/Applemango_Backend/auth/dto/request/LoginRequest.java
  src/main/java/com/Applemango_Backend/auth/dto/request/UpdateUserDto.java
  src/main/java/com/Applemango_Backend/auth/dto/response/GlobalResDto.java
  src/main/java/com/Applemango_Backend/auth/dto/response/TokenDto.java
  src/main/java/com/Applemango_Backend/auth/dto/response/UserDto.java
  src/main/java/com/Applemango_Backend/auth/jwt/JwtTokenFilter.java
  src/main/java/com/Applemango_Backend/auth/jwt/JwtTokenUtil.java
  src/main/java/com/Applemango_Backend/auth/jwt/PrincipalDetails.java
  src/main/java/com/Applemango_Backend/auth/oauth/service/KakaoService.java
  src/main/java/com/Applemango_Backend/auth/service/UserService.java
  src/main/java/com/Applemango_Backend/bookmark/controller/BookmarkController.java
  src/main/java/com/Applemango_Backend/bookmark/domain/Bookmark.java
  src/main/java/com/Applemango_Backend/bookmark/domain/BookmarkRestaurant.java
  src/main/java/com/Applemango_Backend/bookmark/dto/AddBookmarkRestaurantDto.java
  src/main/java/com/Applemango_Backend/bookmark/dto/BookmarkDto.java
  src/main/java/com/Applemango_Backend/bookmark/dto/BookmarkRestaurantDto.java
  src/main/java/com/Applemango_Backend/bookmark/repository/BookmarkRepository.java
  src/main/java/com/Applemango_Backend/bookmark/repository/BookmarkRestaurantRepository.java
  src/main/java/com/Applemango_Backend/bookmark/service/BookmarkService.java
  src/main/java/com/Applemango_Backend/image/service/ImageUploadService.java
Labels: feat, 조종현

#29 [feat] #25 CorsFilter 생성
  src/main/java/com/Applemango_Backend/CorsFilter.java
Labels: feat, 조종현

#31 [feat] #30 리뷰 crud 구현
  src/main/java/com/Applemango_Backend/ApplemangoBackendApplication.java
  src/main/java/com/Applemango_Backend/auth/config/JwtSecurityConfig.java
  src/main/java/com/Applemango_Backend/review/controller/ReviewController.java
  src/main/java/com/Applemango_Backend/review/domain/Review.java
  src/main/java/com/Applemango_Backend/review/domain/ReviewImage.java
  src/main/java/com/Applemango_Backend/review/dto/GetReviewRes.java
  src/main/java/com/Applemango_Backend/review/dto/PatchReviewReq.java
  src/main/java/com/Applemango_Backend/review/dto/PostReviewReq.java
  src/main/java/com/Applemango_Backend/review/repository/ReviewImageRepository.java
  src/main/java/com/Applemango_Backend/review/repository/ReviewRepository.java
  src/main/java/com/Applemango_Backend/review/service/ReviewService.java
Labels: feat, 이다빈

#32 [feat] #25 access-control-allow-headers 추가
  src/main/java/com/Applemango_Backend/CorsFilter.java
Labels: feat, 조종현

#33 [fix] #25 jwtTokenUtil 수정
  src/main/java/com/Applemango_Backend/auth/jwt/JwtTokenUtil.java
Labels: fix, 조종현

#34 [refactor] Api Response 객체 도입
  src/main/java/com/Applemango_Backend/exception/ApiException.java
  src/main/java/com/Applemango_Backend/exception/ApiResponse.java
  src/main/java/com/Applemango_Backend/exception/ApiResponseStatus.java
Labels: refactor, 이다빈

#36 [refactor] #35 리뷰기능에 ApiResponse 적용
  src/main/java/com/Applemango_Backend/review/controller/ReviewController.java
  src/main/java/com/Applemango_Backend/review/service/ReviewService.java
Labels: refactor, 이다빈

#37 [feat] #25 request 수정
  src/main/java/com/Applemango_Backend/CorsFilter.java
Labels: feat, 조종현

#38 [feat] #25 corsFilter 수정
  src/main/java/com/Applemango_Backend/CorsFilter.java
Labels: feat, 조종현

#39 [feat] #25 corsfilter 수정
  src/main/java/com/Applemango_Backend/CorsFilter.java
Labels: feat, 조종현

#41 [refactor] #40 ApiResponse 적용
  src/main/java/com/Applemango_Backend/auth/controller/JwtLoginController.java
  src/main/java/com/Applemango_Backend/auth/controller/UserController.java
  src/main/java/com/Applemango_Backend/auth/repository/RefreshTokenRepository.java
  src/main/java/com/Applemango_Backend/auth/service/UserService.java
  src/main/java/com/Applemango_Backend/bookmark/controller/BookmarkController.java
  src/main/java/com/Applemango_Backend/bookmark/service/BookmarkService.java
Labels: refactor, 조종현

#42 [refactor] #40 login response에 token 추가
  src/main/java/com/Applemango_Backend/auth/controller/JwtLoginController.java
  src/main/java/com/Applemango_Backend/auth/dto/response/LoginUserDto.java
  src/main/java/com/Applemango_Backend/auth/service/UserService.java
Labels: refactor, 조종현

#44 [feat] #43 내가 작성한 리뷰 조회 구현
  src/main/java/com/Applemango_Backend/review/controller/ReviewController.java
  src/main/java/com/Applemango_Backend/review/repository/ReviewRepository.java
  src/main/java/com/Applemango_Backend/review/service/ReviewService.java
Labels: feat, 이다빈

#46 [refactor] #45 리뷰기능에 토큰 검증 및 인가 추가
  src/main/java/com/Applemango_Backend/review/controller/ReviewController.java
  src/main/java/com/Applemango_Backend/review/dto/PostReviewReq.java
  src/main/java/com/Applemango_Backend/review/service/ReviewService.java
Labels: refactor, 이다빈

#48 [refactor] #47 리뷰조회에 리뷰 평균평점 추가
  src/main/java/com/Applemango_Backend/review/controller/ReviewController.java
  src/main/java/com/Applemango_Backend/review/dto/GetReviewAndAvg.java
  src/main/java/com/Applemango_Backend/review/repository/ReviewRepository.java
  src/main/java/com/Applemango_Backend/review/service/ReviewService.java
Labels: refactor, 이다빈
