Repository AppleMangoPlate/AppleMangoPlate_Backend, pull requests merged in 2023-10, with the labels that each got.

#6 [feat] 카카오 소셜 로그인 구현
  build.gradle
  src/main/java/com/Applemango_Backend/auth/config/JwtSecurityConfig.java
  src/main/java/com/Applemango_Backend/auth/oauth/controller/KakaoController.java
  src/main/java/com/Applemango_Backend/auth/oauth/domain/KakaoUserInfo.java
  src/main/java/com/Applemango_Backend/auth/oauth/dto/KakaoLoginResponse.java
  src/main/java/com/Applemango_Backend/auth/oauth/dto/KakaoTokenDto.java
  src/main/java/com/Applemango_Backend/auth/oauth/service/KakaoService.java
  src/main/java/com/Applemango_Backend/auth/oauth/service/Oauth2UserService.java
Labels: feat, 이다빈

#10 [feat] #7 카테고리 검색
  build.gradle
  src/main/java/com/Applemango_Backend/auth/config/JwtSecurityConfig.java
  src/main/java/com/Applemango_Backend/auth/service/UserService.java
  src/main/java/com/Applemango_Backend/search/controller/CategoryController.java
  src/main/java/com/Applemango_Backend/search/service/CategoryService.java
Labels: feat, 조종현

#11 [feat] #9 회원가입 객체에 GCS로 프로필이미지 추가
  .gitignore
  build.gradle
  src/main/java/com/Applemango_Backend/auth/controller/JwtLoginController.java
  src/main/java/com/Applemango_Backend/auth/domain/User.java
  src/main/java/com/Applemango_Backend/auth/dto/JoinRequest.java
  src/main/java/com/Applemango_Backend/auth/service/UserService.java
  src/main/java/com/Applemango_Backend/image/config/StorageConfig.java
  src/main/java/com/Applemango_Backend/image/service/ImageUploadService.java
Labels: feat, 조종현

#13 [refactor] #12 이메일 중복 메서드 분리
  src/main/java/com/Applemango_Backend/auth/controller/JwtLoginController.java
  src/main/java/com/Applemango_Backend/auth/service/UserService.java
Labels: refactor, 조종현

#16 [refactor] #15 카카오 소셜 로그인 예외처리 및 설정파일 수정
  build.gradle
  src/main/java/com/Applemango_Backend/auth/oauth/service/KakaoService.java
Labels: refactor, 이다빈
